apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: 192.168.0.51:5000/bank-system/api-gateway
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: incomes
  namespace: bank
  labels:
    app: incomes
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: incomes
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
