version: '3.8'

services:
  webserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - api-gateway-network

networks:
  api-gateway-network:
    name: bank-system_api-gateway-network
    external: true
